name: sims_mod_manager
description: Cross-platform desktop mod manager for The Sims series (and future moddable games).
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
