// GENERATED by tool/gen_pack_catalog.dart - do not edit.
//
// Every pack the four games shipped, under the codes the games use
// for themselves. The portal offers these when a creator says which
// packs their mod needs, and the app checks the codes that come back
// against what is actually installed. The names come straight out of
// the app's own tables, so neither side can start calling EP01
// something the other does not.

export interface CatalogPack {
  code: string;
  name: string;
  kind: 'expansion' | 'gamePack' | 'stuff' | 'kit' | 'free';
}

export const packCatalog: Record<string, CatalogPack[]> = {
  sims1: [
    { code: "EP01", name: "Livin’ Large", kind: "expansion" },
    { code: "EP02", name: "House Party", kind: "expansion" },
    { code: "EP03", name: "Hot Date", kind: "expansion" },
    { code: "EP04", name: "Vacation", kind: "expansion" },
    { code: "EP05", name: "Unleashed", kind: "expansion" },
    { code: "EP06", name: "Superstar", kind: "expansion" },
    { code: "EP07", name: "Makin’ Magic", kind: "expansion" },
  ],
  sims2: [
    { code: "EP01", name: "University", kind: "expansion" },
    { code: "EP02", name: "Nightlife", kind: "expansion" },
    { code: "EP03", name: "Open for Business", kind: "expansion" },
    { code: "EP04", name: "Pets", kind: "expansion" },
    { code: "EP05", name: "Seasons", kind: "expansion" },
    { code: "EP06", name: "Bon Voyage", kind: "expansion" },
    { code: "EP07", name: "FreeTime", kind: "expansion" },
    { code: "EP08", name: "Apartment Life", kind: "expansion" },
    { code: "EP09", name: "Mansion & Garden Stuff", kind: "expansion" },
    { code: "SP01", name: "Family Fun Stuff", kind: "stuff" },
    { code: "SP02", name: "Glamour Life Stuff", kind: "stuff" },
    { code: "SP04", name: "Celebration! Stuff", kind: "stuff" },
    { code: "SP05", name: "H&M Fashion Stuff", kind: "stuff" },
    { code: "SP06", name: "Teen Style Stuff", kind: "stuff" },
    { code: "SP07", name: "Kitchen & Bath Interior Design Stuff", kind: "stuff" },
    { code: "SP08", name: "IKEA Home Stuff", kind: "stuff" },
  ],
  sims3: [
    { code: "EP01", name: "World Adventures", kind: "expansion" },
    { code: "EP02", name: "Ambitions", kind: "expansion" },
    { code: "EP03", name: "Late Night", kind: "expansion" },
    { code: "EP04", name: "Generations", kind: "expansion" },
    { code: "EP05", name: "Pets", kind: "expansion" },
    { code: "EP06", name: "Showtime", kind: "expansion" },
    { code: "EP07", name: "Supernatural", kind: "expansion" },
    { code: "EP08", name: "Seasons", kind: "expansion" },
    { code: "EP09", name: "University Life", kind: "expansion" },
    { code: "EP10", name: "Island Paradise", kind: "expansion" },
    { code: "EP11", name: "Into the Future", kind: "expansion" },
    { code: "SP01", name: "High-End Loft Stuff", kind: "stuff" },
    { code: "SP02", name: "Fast Lane Stuff", kind: "stuff" },
    { code: "SP03", name: "Outdoor Living Stuff", kind: "stuff" },
    { code: "SP04", name: "Town Life Stuff", kind: "stuff" },
    { code: "SP05", name: "Master Suite Stuff", kind: "stuff" },
    { code: "SP06", name: "Katy Perry's Sweet Treats", kind: "stuff" },
    { code: "SP07", name: "Diesel Stuff", kind: "stuff" },
    { code: "SP08", name: "70s, 80s & 90s Stuff", kind: "stuff" },
    { code: "SP09", name: "Movie Stuff", kind: "stuff" },
  ],
  sims4: [
    { code: "EP01", name: "Get to Work", kind: "expansion" },
    { code: "EP02", name: "Get Together", kind: "expansion" },
    { code: "EP03", name: "City Living", kind: "expansion" },
    { code: "EP04", name: "Cats & Dogs", kind: "expansion" },
    { code: "EP05", name: "Seasons", kind: "expansion" },
    { code: "EP06", name: "Get Famous", kind: "expansion" },
    { code: "EP07", name: "Island Living", kind: "expansion" },
    { code: "EP08", name: "Discover University", kind: "expansion" },
    { code: "EP09", name: "Eco Lifestyle", kind: "expansion" },
    { code: "EP10", name: "Snowy Escape", kind: "expansion" },
    { code: "EP11", name: "Cottage Living", kind: "expansion" },
    { code: "EP12", name: "High School Years", kind: "expansion" },
    { code: "EP13", name: "Growing Together", kind: "expansion" },
    { code: "EP14", name: "Horse Ranch", kind: "expansion" },
    { code: "EP15", name: "For Rent", kind: "expansion" },
    { code: "EP16", name: "Lovestruck", kind: "expansion" },
    { code: "EP17", name: "Life & Death", kind: "expansion" },
    { code: "EP18", name: "Businesses & Hobbies", kind: "expansion" },
    { code: "EP19", name: "Enchanted by Nature", kind: "expansion" },
    { code: "EP20", name: "Adventure Awaits", kind: "expansion" },
    { code: "EP21", name: "Royalty & Legacy", kind: "expansion" },
    { code: "FP01", name: "Holiday Celebration Pack", kind: "free" },
    { code: "GP01", name: "Outdoor Retreat", kind: "gamePack" },
    { code: "GP02", name: "Spa Day", kind: "gamePack" },
    { code: "GP03", name: "Dine Out", kind: "gamePack" },
    { code: "GP04", name: "Vampires", kind: "gamePack" },
    { code: "GP05", name: "Parenthood", kind: "gamePack" },
    { code: "GP06", name: "Jungle Adventure", kind: "gamePack" },
    { code: "GP07", name: "StrangerVille", kind: "gamePack" },
    { code: "GP08", name: "Realm of Magic", kind: "gamePack" },
    { code: "GP09", name: "Star Wars: Journey to Batuu", kind: "gamePack" },
    { code: "GP10", name: "Dream Home Decorator", kind: "gamePack" },
    { code: "GP11", name: "My Wedding Stories", kind: "gamePack" },
    { code: "GP12", name: "Werewolves", kind: "gamePack" },
    { code: "SP01", name: "Luxury Party Stuff", kind: "stuff" },
    { code: "SP02", name: "Perfect Patio Stuff", kind: "stuff" },
    { code: "SP03", name: "Cool Kitchen Stuff", kind: "stuff" },
    { code: "SP04", name: "Spooky Stuff", kind: "stuff" },
    { code: "SP05", name: "Movie Hangout Stuff", kind: "stuff" },
    { code: "SP06", name: "Romantic Garden Stuff", kind: "stuff" },
    { code: "SP07", name: "Kids Room Stuff", kind: "stuff" },
    { code: "SP08", name: "Backyard Stuff", kind: "stuff" },
    { code: "SP09", name: "Vintage Glamour Stuff", kind: "stuff" },
    { code: "SP10", name: "Bowling Night Stuff", kind: "stuff" },
    { code: "SP11", name: "Fitness Stuff", kind: "stuff" },
    { code: "SP12", name: "Toddler Stuff", kind: "stuff" },
    { code: "SP13", name: "Laundry Day Stuff", kind: "stuff" },
    { code: "SP14", name: "My First Pet Stuff", kind: "stuff" },
    { code: "SP15", name: "Moschino Stuff", kind: "stuff" },
    { code: "SP16", name: "Tiny Living", kind: "stuff" },
    { code: "SP17", name: "Nifty Knitting", kind: "stuff" },
    { code: "SP18", name: "Paranormal Stuff", kind: "stuff" },
    { code: "SP20", name: "Throwback Fit Kit", kind: "kit" },
    { code: "SP21", name: "Country Kitchen Kit", kind: "kit" },
    { code: "SP22", name: "Bust the Dust Kit", kind: "kit" },
    { code: "SP23", name: "Courtyard Oasis Kit", kind: "kit" },
    { code: "SP24", name: "Fashion Street Kit", kind: "kit" },
    { code: "SP25", name: "Industrial Loft Kit", kind: "kit" },
    { code: "SP26", name: "Incheon Arrivals Kit", kind: "kit" },
    { code: "SP28", name: "Modern Menswear Kit", kind: "kit" },
    { code: "SP29", name: "Blooming Rooms Kit", kind: "kit" },
    { code: "SP30", name: "Carnaval Streetwear Kit", kind: "kit" },
    { code: "SP31", name: "Décor to the Max Kit", kind: "kit" },
    { code: "SP32", name: "Moonlight Chic Kit", kind: "kit" },
    { code: "SP33", name: "Little Campers Kit", kind: "kit" },
    { code: "SP34", name: "First Fits Kit", kind: "kit" },
    { code: "SP35", name: "Desert Luxe Kit", kind: "kit" },
    { code: "SP36", name: "Pastel Pop Kit", kind: "kit" },
    { code: "SP37", name: "Everyday Clutter Kit", kind: "kit" },
    { code: "SP38", name: "Simtimates Collection Kit", kind: "kit" },
    { code: "SP39", name: "Bathroom Clutter Kit", kind: "kit" },
    { code: "SP40", name: "Greenhouse Haven Kit", kind: "kit" },
    { code: "SP41", name: "Basement Treasures Kit", kind: "kit" },
    { code: "SP42", name: "Grunge Revival Kit", kind: "kit" },
    { code: "SP43", name: "Book Nook Kit", kind: "kit" },
    { code: "SP44", name: "Poolside Splash Kit", kind: "kit" },
    { code: "SP45", name: "Modern Luxe Kit", kind: "kit" },
    { code: "SP46", name: "Home Chef Hustle", kind: "stuff" },
    { code: "SP47", name: "Castle Estate Kit", kind: "kit" },
    { code: "SP48", name: "Goth Galore Kit", kind: "kit" },
    { code: "SP49", name: "Crystal Creations", kind: "stuff" },
    { code: "SP50", name: "Urban Homage Kit", kind: "kit" },
    { code: "SP51", name: "Party Essentials Kit", kind: "kit" },
    { code: "SP52", name: "Riviera Retreat Kit", kind: "kit" },
    { code: "SP53", name: "Cozy Bistro Kit", kind: "kit" },
    { code: "SP54", name: "Artist Studio Kit", kind: "kit" },
    { code: "SP55", name: "Storybook Nursery Kit", kind: "kit" },
    { code: "SP56", name: "Sweet Slumber Party Kit", kind: "kit" },
    { code: "SP57", name: "Cozy Kitsch Kit", kind: "kit" },
    { code: "SP58", name: "Comfy Gamer Kit", kind: "kit" },
    { code: "SP59", name: "Secret Sanctuary Kit", kind: "kit" },
    { code: "SP60", name: "Casanova Cave Kit", kind: "kit" },
    { code: "SP61", name: "Refined Livingroom Kit", kind: "kit" },
    { code: "SP62", name: "Business Chic Kit", kind: "kit" },
    { code: "SP63", name: "Sleek Bathroom Kit", kind: "kit" },
    { code: "SP64", name: "Sweet Allure Kit", kind: "kit" },
    { code: "SP65", name: "Restoration Workshop Kit", kind: "kit" },
    { code: "SP66", name: "Golden Years Kit", kind: "kit" },
    { code: "SP67", name: "Kitchen Clutter Kit", kind: "kit" },
    { code: "SP68", name: "SpongeBob's House Kit", kind: "kit" },
    { code: "SP69", name: "Autumn Apparel Kit", kind: "kit" },
    { code: "SP70", name: "SpongeBob Kid's Room Kit", kind: "kit" },
    { code: "SP71", name: "Grange Mudroom Kit", kind: "kit" },
    { code: "SP72", name: "Essential Glam Kit", kind: "kit" },
    { code: "SP73", name: "Modern Retreat Kit", kind: "kit" },
    { code: "SP74", name: "Garden to Table Kit", kind: "kit" },
    { code: "SP75", name: "Wonderland Playroom Kit", kind: "kit" },
    { code: "SP76", name: "Silver Screen Style Kit", kind: "kit" },
    { code: "SP77", name: "Tea Time Solarium Kit", kind: "kit" },
    { code: "SP78", name: "Lady Bridgerton's Masquerade Ball Fashion Kit", kind: "kit" },
    { code: "SP79", name: "Lady Bridgerton's Masquerade Ballroom Kit", kind: "kit" },
    { code: "SP81", name: "Prairie Dreams Kit", kind: "kit" },
    { code: "SP82", name: "Yard Charm Kit", kind: "kit" },
  ],
};

/// The pack a code stands for, for a listing that names one.
export const packName = (gameId: string, code: string): string =>
  packCatalog[gameId]?.find((pack) => pack.code === code)?.name ?? code;

/// What a stored requirement code is allowed to look like. Kept in step
/// with normalizePackCode in lib/src/core/pack_requirements.dart: both
/// sides read these out of a document a stranger could have written.
export const packCodePattern = /^[A-Z0-9]{2,12}$/;

export const maxPackRequirements = 24;

/// The codes of [raw] we are willing to keep, uppercased, deduped and
/// capped. Anything else is dropped rather than shown as itself.
export function normalizePackCodes(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  const codes: string[] = [];
  for (const entry of raw) {
    if (typeof entry !== 'string') continue;
    const code = entry.trim().toUpperCase();
    if (!packCodePattern.test(code) || codes.includes(code)) continue;
    codes.push(code);
    if (codes.length === maxPackRequirements) break;
  }
  return codes;
}
