import 'dart:convert';
import 'dart:io';

import 'package:sims_mod_manager/src/games/the_sims/sims1_packs.dart';
import 'package:sims_mod_manager/src/games/the_sims/sims2_packs.dart';
import 'package:sims_mod_manager/src/games/the_sims/sims4_packs.dart';

/// Fetches the pack artwork the app ships for the games that keep none a
/// reader can reach, and writes it into `assets/packs/<game>/<CODE>.png`.
///
/// The Sims 3 is absent on purpose: every one of its packs carries its own
/// icon beside its executable, so the app reads those off the player's
/// disk instead. The other three ship nothing usable - The Sims 4's art is
/// DDS inside a shared archive with nothing to say which pack owns which
/// image, The Sims 2 has only the collection-level bundle logos, and The
/// Sims 1 merged its expansions on install - so their icons come from
/// here.
///
/// Run after a new pack is released:
///
///   dart tool/fetch_pack_icons.dart            # only what is missing
///   dart tool/fetch_pack_icons.dart --force    # re-fetch everything
///
/// Coverage is expected to be partial and that is fine: a pack with no
/// artwork draws its own code instead, which is what the app did for all
/// of them before this existed.
const _api = 'https://sims.fandom.com/api.php';

/// Fandom refuses a request that does not look like a browser.
const _userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)';

/// Wide enough to stay sharp on a scaled display at the size the packs
/// screen draws them, small enough that a hundred of them are not a
/// download.
const _width = 128;

/// Titles per request. The API takes fifty, which turns a candidate list
/// of several hundred into a dozen round trips.
const _batch = 50;

void main(List<String> args) async {
  final force = args.contains('--force');
  final client = HttpClient()..userAgent = _userAgent;
  var written = 0;
  var missing = <String>[];

  for (final game in _games) {
    final dir = Directory('assets/packs/${game.id}');
    await dir.create(recursive: true);

    // Every name this pack's artwork might be filed under, flattened so
    // the whole game costs a handful of requests rather than one each.
    final candidates = <String, List<String>>{
      for (final entry in game.packs.entries)
        entry.key: game.candidates(entry.value),
    };
    final found = await _resolve(
        client, {for (final list in candidates.values) ...list});

    for (final entry in candidates.entries) {
      if (!force && _existing(dir, entry.key) != null) continue;
      // First candidate that exists wins, so the order in [candidates]
      // is the preference: a square icon before a wordmark before art.
      var url = entry.value.map((c) => found[c]).whereType<String>().firstOrNull;
      // Nothing under a name worth guessing: ask the wiki what it does
      // have filed near this pack's own. The older kits are the reason -
      // they are filed as "Country Kitchen Kit.png" rather than with an
      // "Icon" suffix, and one of them is filed under a different name
      // than the store ever used.
      url ??= await _fromPage(client, game.pageTitle, game.packs[entry.key]!);
      url ??= await _discover(client, game.packs[entry.key]!);
      if (url == null) {
        missing.add('${game.id}/${entry.key} ${game.packs[entry.key]}');
        continue;
      }
      final bytes = await _get(client, url);
      final extension = bytes == null ? null : _extensionOf(bytes);
      if (bytes == null || bytes.isEmpty || extension == null) {
        missing.add('${game.id}/${entry.key} (download failed)');
        continue;
      }
      // What arrives decides the name, so a re-fetch that comes back in
      // another format would otherwise leave both files standing - and
      // the manifest lists one code twice, which a const map cannot hold.
      final stale = _existing(dir, entry.key);
      if (stale != null && !stale.path.endsWith(extension)) stale.deleteSync();
      await File('${dir.path}/${entry.key}$extension').writeAsBytes(bytes);
      written++;
      stdout.writeln('${game.id}/${entry.key}$extension  ${bytes.length}b  '
          '${game.packs[entry.key]}');
    }
  }

  client.close();
  await _writeManifest();
  stdout.writeln('\nwrote $written, ${missing.length} without artwork');
  for (final m in missing) {
    stdout.writeln('  $m');
  }
}

/// Writes the list of codes the app actually ships artwork for.
///
/// Generated rather than probed at runtime: asking the bundle for an
/// asset that is not there costs an exception and a line of log per pack
/// per build, and this way a test can hold the list and the folder to
/// each other.
Future<void> _writeManifest() async {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/fetch_pack_icons.dart - do not edit.')
    ..writeln('//')
    ..writeln('// The packs the app ships artwork for. The Sims 3 is absent')
    ..writeln('// because its packs carry their own icons on disk, and the')
    ..writeln('// games here are missing whichever packs nothing could be')
    ..writeln('// found for - those draw their own code instead.')
    ..writeln()
    ..writeln('const packIconFiles = <String, Map<String, String>>{');
  for (final game in _games) {
    final dir = Directory('assets/packs/${game.id}');
    if (!dir.existsSync()) continue;
    final files = dir
        .listSync()
        .whereType<File>()
        .map((f) => f.uri.pathSegments.last)
        .where((n) => _extensions.values.any(n.endsWith))
        .toList()
      ..sort();
    if (files.isEmpty) continue;
    buffer.writeln("  '${game.id}': {");
    for (final name in files) {
      final code = name.substring(0, name.lastIndexOf('.'));
      buffer.writeln("    '$code': '$name',");
    }
    buffer.writeln('  },');
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('/// The artwork shipped for [code] of [gameId], or null when')
    ..writeln('/// there is none and the pack should draw its own code.')
    ..writeln('String? packIconAsset(String gameId, String code) {')
    ..writeln('  final name = packIconFiles[gameId]?[code];')
    ..writeln("  return name == null ? null : 'assets/packs/\$gameId/\$name';")
    ..writeln('}');
  await File('lib/src/ui/pack_icons.dart').writeAsString(buffer.toString());
}

/// The artwork already on disk for [code], whatever it was saved as.
File? _existing(Directory dir, String code) {
  for (final extension in _extensions.values) {
    final file = File('${dir.path}/$code$extension');
    if (file.existsSync()) return file;
  }
  return null;
}

/// Leading bytes -> the extension the file should carry.
///
/// The wiki's thumbnailer answers in whichever format it likes, so what
/// arrives decides the name rather than what was asked for; Flutter draws
/// all three and the app already ships a WebP for one of the games.
const _extensions = <String, String>{
  '89504e47': '.png',
  'ffd8ffe0': '.jpg',
  'ffd8ffe1': '.jpg',
  'ffd8ffdb': '.jpg',
  '52494646': '.webp',
};

String? _extensionOf(List<int> bytes) {
  if (bytes.length < 12) return null;
  final head = bytes
      .take(4)
      .map((b) => b.toRadixString(16).padLeft(2, '0'))
      .join();
  final extension = _extensions[head];
  if (extension != '.webp') return extension;
  // RIFF is a container; only the WEBP flavour of it is an image.
  final form = String.fromCharCodes(bytes.sublist(8, 12));
  return form == 'WEBP' ? '.webp' : null;
}

/// Maps every candidate file title to a thumbnail URL, skipping the ones
/// the wiki does not have. Only PNGs are taken: the covers filed as JPEG
/// are photographs of a box, which say far less at this size than the
/// pack's own icon does.
Future<Map<String, String>> _resolve(
    HttpClient client, Set<String> titles) async {
  final all = titles.toList();
  final found = <String, String>{};
  for (var i = 0; i < all.length; i += _batch) {
    final slice = all.sublist(i, (i + _batch).clamp(0, all.length));
    final query = Uri.parse(_api).replace(queryParameters: {
      'action': 'query',
      'prop': 'imageinfo',
      'iiprop': 'url|mime',
      'iiurlwidth': '$_width',
      'format': 'json',
      'titles': slice.map((t) => 'File:$t').join('|'),
    });
    final body = await _get(client, query.toString());
    if (body == null) continue;
    final Map<String, dynamic> decoded =
        jsonDecode(utf8.decode(body)) as Map<String, dynamic>;
    final pages =
        (decoded['query'] as Map<String, dynamic>?)?['pages'] as Map<String, dynamic>?;
    if (pages == null) continue;
    // Titles come back normalized (underscores, capitalization), so the
    // reply has to be matched to what was asked rather than assumed.
    final normalized = <String, String>{
      for (final t in slice) _key(t): t,
    };
    for (final page in pages.values) {
      final map = page as Map<String, dynamic>;
      if (map.containsKey('missing')) continue;
      final info = (map['imageinfo'] as List<dynamic>?)?.firstOrNull
          as Map<String, dynamic>?;
      final url = (info?['thumburl'] ?? info?['url']) as String?;
      if (url == null || info?['mime'] != 'image/png') continue;
      final asked = normalized[_key((map['title'] as String).substring(5))];
      if (asked != null) found[asked] = url;
    }
    await Future<void>.delayed(const Duration(milliseconds: 150));
  }
  return found;
}

String _key(String title) =>
    title.replaceAll('_', ' ').toLowerCase().trim();

Set<String> _words(String value) => value
    .toLowerCase()
    .split(RegExp(r'[^a-z0-9]+'))
    .where((w) => w.length > 2 && !const {'the', 'kit', 'icon', 'png'}.contains(w))
    .toSet();

/// Looks for artwork filed near [name] rather than under a name this
/// script guessed, and returns the best match's thumbnail - or null when
/// nothing there is convincingly about this pack.
///
/// Deliberately strict: a pack drawn with another pack's picture is worse
/// than one drawn with its own code, so a candidate has to share a real
/// word with the pack's name and look like a pack image rather than a
/// screenshot of one of its objects.
Future<String?> _discover(HttpClient client, String name) async {
  final wanted = _words(name);
  if (wanted.isEmpty) return null;
  final prefix = name.split(' ').first;
  final query = Uri.parse(_api).replace(queryParameters: {
    'action': 'query',
    'list': 'allimages',
    'ailimit': '60',
    'format': 'json',
    'aiprefix': prefix,
  });
  final body = await _get(client, query.toString());
  await Future<void>.delayed(const Duration(milliseconds: 150));
  if (body == null) return null;
  final decoded = jsonDecode(utf8.decode(body)) as Map<String, dynamic>;
  final images =
      (decoded['query'] as Map<String, dynamic>?)?['allimages'] as List<dynamic>?;
  if (images == null) return null;

  String? best;
  var bestScore = 0;
  for (final image in images) {
    final map = image as Map<String, dynamic>;
    final title = (map['name'] as String).replaceAll('_', ' ');
    if (!title.toLowerCase().endsWith('.png')) continue;
    final have = _words(title);
    final shared = wanted.where(have.contains).length;
    if (shared == 0) continue;
    // Every word of the pack's name, or all but one on the longer ones.
    if (shared < wanted.length - (wanted.length > 2 ? 1 : 0)) continue;
    var score = shared * 2;
    final lower = title.toLowerCase();
    if (lower.contains('icon')) score += 3;
    if (lower.contains('kit')) score += 2;
    // A numbered file is one of the pack's screenshots, not the pack.
    if (RegExp(r'\d\.png$').hasMatch(lower)) score -= 3;
    if (score > bestScore) {
      bestScore = score;
      best = (map['url'] as String?);
      final thumb = map['thumburl'] as String?;
      best = thumb ?? best;
    }
  }
  if (best == null || bestScore < 4) return null;
  // allimages hands back the full-size file; ask for it at drawing size.
  return best.replaceFirst(
      RegExp(r'/revision/latest.*$'), '/revision/latest/scale-to-width-down/$_width');
}

Future<List<int>?> _get(HttpClient client, String url) async {
  for (var attempt = 0; attempt < 3; attempt++) {
    try {
      final request = await client.getUrl(Uri.parse(url));
      final response = await request.close();
      if (response.statusCode != 200) {
        await response.drain<void>();
        return null;
      }
      final bytes = <int>[];
      await for (final chunk in response) {
        bytes.addAll(chunk);
      }
      return bytes;
    } catch (_) {
      await Future<void>.delayed(Duration(milliseconds: 400 * (attempt + 1)));
    }
  }
  return null;
}

/// Artwork that belongs to the series rather than to any one pack, and
/// sits on nearly every page. Picking one of these would put the same
/// picture on a hundred cards.
const _generic = {
  'ts4 icon',
  'ts3 icon',
  'ts2 icon',
  'the sims icon',
  'the sims 2 icon',
  'the sims 3 icon',
  'the sims 4 icon',
  'film icon',
  'ts4 star trophy icon',
};

/// The best icon on the pack's own wiki page.
///
/// This is where the older Sims 4 packs keep theirs, filed under initials
/// - Get to Work's is `TS4GTW Icon.png` - which no amount of guessing at
/// full names would find.
Future<String?> _fromPage(
    HttpClient client, String pageTitle, String name) async {
  final query = Uri.parse(_api).replace(queryParameters: {
    'action': 'query',
    'prop': 'images',
    'imlimit': '80',
    'format': 'json',
    'titles': '$pageTitle$name',
  });
  final body = await _get(client, query.toString());
  await Future<void>.delayed(const Duration(milliseconds: 150));
  if (body == null) return null;
  final decoded = jsonDecode(utf8.decode(body)) as Map<String, dynamic>;
  final pages =
      (decoded['query'] as Map<String, dynamic>?)?['pages'] as Map<String, dynamic>?;
  if (pages == null) return null;

  final wanted = _words(name);
  final initials = _initials(name).toLowerCase();
  String? best;
  var bestScore = 0;
  for (final page in pages.values) {
    final map = page as Map<String, dynamic>;
    for (final image in (map['images'] as List<dynamic>? ?? const [])) {
      final title = ((image as Map<String, dynamic>)['title'] as String)
          .substring(5)
          .replaceAll('_', ' ');
      final lower = title.toLowerCase();
      if (!lower.endsWith('.png')) continue;
      final stem = lower.substring(0, lower.length - 4).trim();
      if (_generic.contains(stem)) continue;
      final shared = wanted.where(_words(title).contains).length;
      // Either it names the pack, or it carries the initials the wiki
      // files that pack under.
      final byInitials = initials.length > 1 && stem.contains(initials);
      if (shared == 0 && !byInitials) continue;
      // A file that does not announce itself as the pack's icon has to
      // name the pack completely instead - the kits keep theirs as plain
      // "Country Kitchen Kit.png" - and must not be one of the numbered
      // screenshots sitting beside it on the same page.
      if (!lower.contains('icon')) {
        if (shared < wanted.length) continue;
        if (RegExp(r'\d\.png$').hasMatch(lower)) continue;
      }
      final score = shared * 2 +
          (byInitials ? 4 : 0) +
          (lower.contains('icon') ? 3 : 0) +
          (lower.contains('kit') ? 1 : 0);
      if (score > bestScore) {
        bestScore = score;
        best = title;
      }
    }
  }
  if (best == null) return null;
  final resolved = await _resolve(client, {best});
  return resolved[best];
}

class _Game {
  const _Game(this.id, this.packs, this.candidates, this.pageTitle);

  final String id;

  /// What the wiki puts in front of a pack's name to make its page title.
  final String pageTitle;

  /// Pack code -> the name the store gave it.
  final Map<String, String> packs;

  /// The file titles that name might be filed under, best first.
  final List<String> Function(String name) candidates;
}

/// The wiki writes "and" where the store writes "&", and both spellings
/// are in use, so every candidate is tried either way.
List<String> _spellings(String name) {
  final out = <String>{name};
  if (name.contains('&')) out.add(name.replaceAll('&', 'and'));
  if (name.contains('’')) {
    out.addAll(out.map((n) => n.replaceAll('’', "'")).toList());
  }
  return out.toList();
}

/// The initials the wiki files some of the older Sims 4 packs under.
/// "Get to Work" is TS4GTW, so the little words count; "Cats & Dogs" is
/// filed spelled out instead, which the other candidates cover.
String _initials(String name, {bool skipSmallWords = false}) => name
    .split(RegExp(r'[^A-Za-z]+'))
    .where((w) =>
        w.isNotEmpty &&
        !(skipSmallWords && const {'to', 'the', 'of', 'and'}.contains(w)))
    .map((w) => w[0].toUpperCase())
    .join();

final _games = <_Game>[
  _Game('sims4', sims4PackNames, (name) => [
        for (final n in _spellings(name)) ...[
          'TS4 $n Icon.png',
          '$n Icon.png',
          'The Sims 4 $n Icon.png',
          'TS4 $n icon.png',
        ],
        'TS4${_initials(name)} Icon.png',
        'TS4${_initials(name, skipSmallWords: true)} Icon.png',
      ], 'The Sims 4: '),
  _Game('sims2', sims2PackNames, (name) => [
        for (final n in _spellings(name)) ...[
          'The Sims 2 $n Icon.png',
          'TS2 $n Icon.png',
          'The Sims 2 $n Logo.png',
        ],
      ], 'The Sims 2: '),
  _Game(
      'sims1',
      {
        for (final entry in sims1PackNames.entries)
          'EP${entry.key.toString().padLeft(2, '0')}': entry.value,
      },
      (name) => [
            for (final n in _spellings(name)) ...[
              'The Sims $n Icon.png',
              'The Sims $n Logo.png',
              '$n Logo.png',
            ],
          ],
      'The Sims: '),
];
