import 'dart:convert';
import 'dart:io';

import 'package:sims_mod_manager/src/core/game_pack.dart';
import 'package:sims_mod_manager/src/games/the_sims/sims1_packs.dart';
import 'package:sims_mod_manager/src/games/the_sims/sims2_packs.dart';
import 'package:sims_mod_manager/src/games/the_sims/sims3_packs.dart';
import 'package:sims_mod_manager/src/games/the_sims/sims4_packs.dart';

/// Writes `web/src/data/packs.ts` from the pack tables the app already
/// ships, so the portal's requirement picker and the app's requirement
/// check are naming the same packs by the same codes.
///
/// A generator rather than a second table kept by hand: `markup.ts` is
/// the cautionary tale, and this one is 156 rows across four games
/// instead of a grammar somebody would notice going wrong. The catalog
/// is only ever the *names* - what a machine actually has installed is
/// read by the adapters and never leaves the app.
///
/// Run after a new pack is added to any of the four tables:
///
///     dart tool/gen_pack_catalog.dart
///
/// `test/site_test.dart` fails if the file on disk stops matching the
/// tables, which is what stops the two drifting when somebody forgets.
void main() {
  final file = File('web/src/data/packs.ts');
  file.writeAsStringSync(renderPackCatalog());
  stdout.writeln('wrote ${file.path}');
}

/// Every game that has packs worth naming, in the order the site lists
/// its games. The Sims Medieval is absent because it has no packs screen
/// at all: its one add-on shares the base game's patch level, so a copy
/// with it is a different install rather than a setting.
const packCatalogGames = <String, String>{
  'sims1': 'sims1PackCatalog',
  'sims2': 'sims2PackNames',
  'sims3': 'sims3PackNames',
  'sims4': 'sims4PackNames',
};

Map<String, Map<String, String>> packCatalog() => {
      'sims1': sims1PackCatalog,
      'sims2': sims2PackNames,
      'sims3': sims3PackNames,
      'sims4': sims4PackNames,
    };

/// What kind each code is, so the portal can group its checklist the way
/// the packs screen groups its shelves.
String packCatalogKind(String gameId, String code) {
  final kind = switch (gameId) {
    'sims2' => sims2PackKind(code),
    'sims4' => sims4PackKind(code),
    // The Sims 1 and 3 shipped expansions and stuff packs and nothing
    // else, and both spell them the same way.
    _ => code.toUpperCase().startsWith('EP')
        ? GamePackKind.expansion
        : GamePackKind.stuff,
  };
  return kind.name;
}

String renderPackCatalog() {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_pack_catalog.dart - do not edit.')
    ..writeln('//')
    ..writeln('// Every pack the four games shipped, under the codes the games use')
    ..writeln('// for themselves. The portal offers these when a creator says which')
    ..writeln('// packs their mod needs, and the app checks the codes that come back')
    ..writeln('// against what is actually installed. The names come straight out of')
    ..writeln("// the app's own tables, so neither side can start calling EP01")
    ..writeln('// something the other does not.')
    ..writeln('')
    ..writeln('export interface CatalogPack {')
    ..writeln('  code: string;')
    ..writeln('  name: string;')
    ..writeln("  kind: 'expansion' | 'gamePack' | 'stuff' | 'kit' | 'free';")
    ..writeln('}')
    ..writeln('')
    ..writeln('export const packCatalog: Record<string, CatalogPack[]> = {');
  final catalog = packCatalog();
  for (final gameId in packCatalogGames.keys) {
    buffer.writeln('  $gameId: [');
    final codes = catalog[gameId]!.keys.toList()..sort();
    for (final code in codes) {
      final name = jsonEncode(catalog[gameId]![code]);
      final kind = jsonEncode(packCatalogKind(gameId, code));
      buffer.writeln(
          '    { code: ${jsonEncode(code)}, name: $name, kind: $kind },');
    }
    buffer.writeln('  ],');
  }
  buffer
    ..writeln('};')
    ..writeln('')
    ..writeln('/// The pack a code stands for, for a listing that names one.')
    ..writeln('export const packName = (gameId: string, code: string): string =>')
    ..writeln('  packCatalog[gameId]?.find((pack) => pack.code === code)?.name ?? code;')
    ..writeln('')
    ..writeln('/// What a stored requirement code is allowed to look like. Kept in step')
    ..writeln('/// with normalizePackCode in lib/src/core/pack_requirements.dart: both')
    ..writeln('/// sides read these out of a document a stranger could have written.')
    ..writeln('export const packCodePattern = /^[A-Z0-9]{2,12}\$/;')
    ..writeln('')
    ..writeln('export const maxPackRequirements = 24;')
    ..writeln('')
    ..writeln('/// The codes of [raw] we are willing to keep, uppercased, deduped and')
    ..writeln('/// capped. Anything else is dropped rather than shown as itself.')
    ..writeln('export function normalizePackCodes(raw: unknown): string[] {')
    ..writeln('  if (!Array.isArray(raw)) return [];')
    ..writeln('  const codes: string[] = [];')
    ..writeln('  for (const entry of raw) {')
    ..writeln("    if (typeof entry !== 'string') continue;")
    ..writeln('    const code = entry.trim().toUpperCase();')
    ..writeln('    if (!packCodePattern.test(code) || codes.includes(code)) continue;')
    ..writeln('    codes.push(code);')
    ..writeln('    if (codes.length === maxPackRequirements) break;')
    ..writeln('  }')
    ..writeln('  return codes;')
    ..writeln('}');
  return buffer.toString();
}
